spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/any_query?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: username
        password: password

springfox:
    documentation:
        swagger-ui:
            enabled: false
